---
# The options in this file can be overridden in 'globals.yml'

# The "temp" files that are created before merge need to stay persistent due
# to the fact that ansible will register a "change" if it has to create them
# again. Persistent files allow for idempotency
container_config_directory: "/var/lib/kolla/config_files"

# The directory to merge custom config files the kolla's config files
node_custom_config: "/etc/kolla/config"

# The project to generate configuration files for
project: ""

# The directory to store the config files on the destination node
node_config_directory: "/etc/kolla/{{ project }}"


###################
# Kolla options
###################

# Which orchestration engine to use. Valid options are [ ANSIBLE, KUBERNETES ]
orchestration_engine: "ANSIBLE"

# Valid options are [ COPY_ONCE, COPY_ALWAYS ]
config_strategy: "COPY_ALWAYS"

# Valid options are [ centos, oraclelinux, ubuntu ]
kolla_base_distro: "centos"
# Valid options are [ binary, source ]
kolla_install_type: "binary"

kolla_internal_vip_address: "{{ kolla_internal_address }}"
kolla_internal_fqdn: "{{ kolla_internal_vip_address }}"
kolla_external_vip_address: "{{ kolla_internal_vip_address }}"
kolla_external_fqdn: "{{ kolla_internal_fqdn if kolla_external_vip_address == kolla_internal_vip_address else kolla_external_vip_address }}"

kolla_enable_sanity_checks: "no"

####################
# Docker options
####################
docker_registry_email:
docker_registry:
docker_namespace: "kolla"
docker_registry_username:

# Valid options are [ never, on-failure, always, unless-stopped ]
docker_restart_policy: "unless-stopped"

# '0' means unlimited retries
docker_restart_policy_retry: "10"

# Common options used throughout Docker
docker_common_options:
    auth_email: "{{ docker_registry_email }}"
    auth_password: "{{ docker_registry_password }}"
    auth_registry: "{{ docker_registry }}"
    auth_username: "{{ docker_registry_username }}"
    environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    restart_policy: "{{ docker_restart_policy }}"
    restart_retries: "{{ docker_restart_policy_retry }}"

####################
# Networking options
####################
network_interface: "eth0"
neutron_external_interface: "eth1"
kolla_external_vip_interface: "{{ network_interface }}"
api_interface: "{{ network_interface }}"
storage_interface: "{{ network_interface }}"
cluster_interface: "{{ network_interface }}"
tunnel_interface: "{{ network_interface }}"
bifrost_network_interface: "{{ network_interface }}"
dns_interface: "{{ network_interface }}"
tunnel_interface_address: "{{ hostvars[inventory_hostname]['ansible_' + tunnel_interface]['ipv4']['address'] if orchestration_engine == 'ANSIBLE' else '0.0.0.0' }}"

# Valid options are [ openvswitch, linuxbridge, sfc, opendaylight ]
neutron_plugin_agent: "opendaylight"

# The default ports used by each service.
ovsdb_port: "6640"

opendaylight_clustering_port: "2550"
opendaylight_restconf_port: "8181"
opendaylight_restconf_port_backup: "8081"
opendaylight_karaf_ssh_port: "8101"
opendaylight_openflow_port: "6653"
opendaylight_ovsdb_port: "6641"

public_protocol: "{{ 'https' if kolla_enable_tls_external | bool else 'http' }}"
internal_protocol: "http"
admin_protocol: "http"

# Optionally allow Kolla to set sysctl values
set_sysctl: "yes"

enable_opendaylight: "yes"
enable_ovsdpdk: "yes"

# Clean images options are specified here
enable_destroy_images: "no"

enable_manila: "no"

##################
# Neutron options
##################
neutron_bgp_router_id: "1.1.1.1"
neutron_bridge_name: "br-ex"
enable_neutron_dvr: "no"
enable_neutron_qos: "no"

#######################
# OpenDaylight Options
#######################
# Set mechanism driver, valid options are [ opendaylight, opendaylight_v2 ]
opendaylight_mechanism_driver: "opendaylight_v2"
enable_opendaylight_l3: "yes"
enable_opendaylight_qos: "no"
enable_opendaylight_legacy_netvirt_conntrack: "no"
opendaylight_features: "odl-mdsal-apidocs,odl-netvirt-openstack"
neutron_generated_config_dir: "{{ playbook_dir }}/generated-config/"

###################
# OVS-DPDK Options
###################
pmd-cpu-mask: "0x2"
ovs_coremask: "0x1"
ovs_mem_channels: ""
ovs_socket_mem: ""
hugepage_mountpoint: ""
pci_whitelist: ""