---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    recurse: yes
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ openvswitch_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
  register: ovs_config_jsons
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ openvswitch_services }}"
  notify:
  - "Restart {{ item.key }} container"

- name: Copying over start-ovs file for openvswitch-vswitchd
  vars:
    service: "{{ openvswitch_services['openvswitch-vswitchd'] }}"
  template:
    src: "{{ role_path }}/templates/start-ovs.j2"
    dest: "{{ node_config_directory }}/openvswitch-vswitchd/start-ovs"
  register: openvswitch_start_ovs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - "Restart openvswitch-vswitchd container"

- name: Copying over start-ovsdb-server files for openvswitch-db-server
  vars:
    service: "{{ openvswitch_services['openvswitch-db-server'] }}"
  template:
    src: "{{ role_path }}/templates/start-ovsdb-server.j2"
    dest: "{{ node_config_directory }}/openvswitch-db-server/start-ovsdb-server"
  register: openvswitch_start_ovsdb_server
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - "Restart openvswitch-db-server container"

- name: Copying ovs-dpdkctl tool
  copy:
    src: tools/ovs-dpdkctl.sh
    dest: "{{ node_config_directory }}/openvswitch-db-server/ovs-dpdkctl.sh"
    mode: 0777

- name: install ovs-dpdkctl service and config
  become: True
  command: "{{ node_config_directory }}/openvswitch-db-server/ovs-dpdkctl.sh install"
  environment:
    CONFIG_FILE: "{{ node_config_directory }}/openvswitch-db-server/ovs-dpdkctl.conf"
    bridge_mappings: "{{ ovs_bridge_mappings }}"
    port_mappings: "{{ ovs_port_mappings }}"
    cidr_mappings: "{{ ovs_cidr_mappings }}"
    ovs_mem_channels: "{{ ovs_mem_channels }}"
    ovs_socket_mem: "{{ ovs_socket_mem }}"
    hugepage_mountpoint: "{{ ovs_hugepage_mountpoint }}"
    ovs_physical_port_policy: "{{ ovs_physical_port_policy }}"


# TODO check the environment change
- name: Check ovs containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
  register: check_ovs_containers
  when:
    - action != "config"
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ openvswitch_services }}"
  notify:
    - "Restart {{ item.key }} container"
